name = "GenPred"
uuid = "18853147-a48b-4210-b87c-350c5f2dc54e"
authors = ["Brian Ward <brian@brianpward.net>"]
version = "0.1.0"

[deps]
Optim = "429524aa-4258-5aef-a3af-852621145aeb"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
